### ISSUE TITLE
Unknown error - programming error

### ISSUE THREAD

**Issue by RekhaBhale** [tabvn/face-recognition-service#1]
Hello sir I'm getting this error while executing this code on Ubuntu. When I click train image button unknown error is shown. Although the trained image is stored in trained folder but it's not updated in database. Would you please just let me know why this is occurred & how to resolve this.

2018-10-13 13:13:22,583] ERROR in app: Exception on /api/train [POST]
Traceback (most recent call last):
  File "/home/amey/face/venv/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/amey/face/venv/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/amey/face/venv/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/amey/face/venv/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/amey/face/venv/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/amey/face/app.py", line 105, in train
    user_id = app.db.insert('INSERT INTO users(name, created) values(?,?)', [name, created])
  File "/home/amey/face/db.py", line 22, in insert
    cursor = self.connection.cursor()
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 139786747606784 and this is thread id 139786474350336
127.0.0.1 - - [13/Oct/2018 13:13:22] "POST /api/train HTTP/1.1" 500 -

**Comment by jos4u** [comment]
You'd closed it, guess you've found solution to it.

**Comment by zeinabfarhoudi** [comment]
Hi,
I have the same problem:
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 139786747606784 and this is thread id 139786474350336
127.0.0.1 - - [13/Oct/2018 13:13:22] "POST /api/train HTTP/1.1" 500 -

**Comment by Amey97** [comment]
Add "check_same_thread=False" in sqlite3.connect(db) and it looks like 
sqlite3.connect(db,check_same_thread=False")
