### ISSUE TITLE
SQLite error

### ISSUE THREAD

**Issue by ayajnik** [tabvn/face-recognition-service#2]
Getting this error when running the app.py file after training the image

Traceback (most recent call last):
  File "C:\Users\ayush\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ayush\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ayush\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\ayush\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\ayush\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ayush\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:/Projects from Yadvi's Laptop/PycharmProjects/image_classifier/app.py", line 107, in train
    user_id = app.db.insert('INSERT INTO users(name, created) values(?,?)', [name, created])
  File "e:\Projects from Yadvi's Laptop\PycharmProjects\image_classifier\db.py", line 22, in insert
    cursor = self.connection.cursor()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 23052 and this is thread id 14488

**Comment by ANASDAVOODTK** [comment]
i got the same error

**Comment by ayajnik** [comment]
Still not able to resolve it though

**Comment by ANASDAVOODTK** [comment]
YHA I found the solution  
in line no 12 just add after db = > .....(db, check_same_thread = False)

**Comment by ranjith-acharya** [comment]
Just make sure you write, 
SQL connection in each Query, because it is not able to connect to the database.
As shown in the photo below you can add the following line in each of the def functions in the db.py file
![SQLite3-Soln](https://user-images.githubusercontent.com/29570552/112870635-0b329000-90dc-11eb-9521-439c32ed5773.png)
